version: '3.8'
services:
  service-a-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app  
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - service-a-db

  service-a-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - service-a-db
  
  service-a-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_a
    ports:
      - "5433:5432"    
networks:
  default:
    external:
      name: microservices_network
